### ISSUE TITLE
Question on Emulator.x

### ISSUE THREAD

**Issue by Jagmn** [elliotnunn/powermac-rom#3]
Sorry for raising issues; they seem to be the easiest way to ask questions!

I'm curious about Emulator.x: it looks like it is the built product of a previous reverse-engineering of the emulator and dynamic recompiler (by "Murph", perhaps?); is the assembly file still available somewhere? If not I'll start having a crack at it.

Thanks!

**Comment by elliotnunn** [comment]
No worries. The assembly file is floating around. Email me privately on elliot (at) nunn ~dot~ io.
